### ISSUE TITLE
State how to install dependencies

### ISSUE THREAD

**Issue by GordanM** [Pelagicore/PeluxDeviceManager#2]
For now the README.md states dependencies but it took me quite a while to install all the needed dependencies. For instance it would be good to know that there is no packages available and you need to build Solid and extra-cmake-modules from source. The stable versions (tag/branch whatever) would be also nice to state in the README.md.

**Comment by caybro** [comment]
Yup, I'll expand that; note that Solid (or any other kf5 frameworks) don't have branches, they just have monthly releases.
